config/routes.rb
Rails.application.routes.draw do
  resources :physicians
  resources :patients
  resources :relatives
  
  root to: 'physicians#index'
  devise_for :users
  resources :users

end

app/models/caretaker.rb
class Caretaker < ActiveRecord::Base
end

app/models/hospital.rb
class Hospital < ActiveRecord::Base
end

app/models/patient.rb
class Patient < ActiveRecord::Base

	has_many :caretakers
	has_many :physicians, :through => :caretakers
	has_many :relatives

	validates :name, :room, :avatar, presence: true

	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }
	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

	# before_save :handle_caretakers

 #  def handle_caretakers
 #    self.caretakers = self.physician_ids.select(&:present?).join(';') 
 #  end

 #  def similars
 #    self.class.find(self.similar_ids.split(';'))
 #  end

end

app/models/physician.rb
class Physician < ActiveRecord::Base
	
	has_many :caretakers
	has_many :patients, :through => :caretakers

	validates :name, :specialty, :avatar, presence: true

	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }
	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

end

app/models/relative.rb
class Relative < ActiveRecord::Base

	belongs_to :patient

	validates :name, presence: true

	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }
	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]

  # GET /patients
  # GET /patients.json
  def index
    @patients = Patient.all
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(patient_params)
    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient, notice: 'Patient was successfully created.' }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_url, notice: 'Patient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_params
      params.require(:patient).permit(:name, :bio, :room, :checkin_date, :release_date, :caretakers, :hospital_id, :avatar)
    end
end

app/controllers/physicians_controller.rb
class PhysiciansController < ApplicationController
  before_action :set_physician, only: [:show, :edit, :update, :destroy]

  # GET /physicians
  # GET /physicians.json
  def index
    @physicians = Physician.all
  end

  # GET /physicians/1
  # GET /physicians/1.json
  def show
  end

  # GET /physicians/new
  def new
    @physician = Physician.new
  end

  # GET /physicians/1/edit
  def edit
  end

  # POST /physicians
  # POST /physicians.json
  def create
    @physician = Physician.new(physician_params)

    respond_to do |format|
      if @physician.save
        format.html { redirect_to @physician, notice: 'Physician was successfully created.' }
        format.json { render :show, status: :created, location: @physician }
      else
        format.html { render :new }
        format.json { render json: @physician.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /physicians/1
  # PATCH/PUT /physicians/1.json
  def update
    respond_to do |format|
      if @physician.update(physician_params)
        format.html { redirect_to @physician, notice: 'Physician was successfully updated.' }
        format.json { render :show, status: :ok, location: @physician }
      else
        format.html { render :edit }
        format.json { render json: @physician.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /physicians/1
  # DELETE /physicians/1.json
  def destroy
    @physician.destroy
    respond_to do |format|
      format.html { redirect_to physicians_url, notice: 'Physician was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_physician
      @physician = Physician.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def physician_params
      params.require(:physician).permit(:name, :bio, :specialty, :hospital_id, :avatar)
    end
end

app/controllers/relatives_controller.rb
class RelativesController < ApplicationController
  before_action :set_relative, only: [:show, :edit, :update, :destroy]

  # GET /relatives
  # GET /relatives.json
  def index
    @relatives = Relative.all
  end

  # GET /relatives/1
  # GET /relatives/1.json
  def show
  end

  # GET /relatives/new
  def new
    @relative = Relative.new
  end

  # GET /relatives/1/edit
  def edit
  end

  # POST /relatives
  # POST /relatives.json
  def create
    @relative = Relative.new(relative_params)
    respond_to do |format|
      if @relative.save
        format.html { redirect_to @relative, notice: 'Relative was successfully created.' }
        format.json { render :show, status: :created, location: @relative }
      else
        format.html { render :new }
        format.json { render json: @relative.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /relatives/1
  # PATCH/PUT /relatives/1.json
  def update
    respond_to do |format|
      if @relative.update(relative_params)
        format.html { redirect_to @relative, notice: 'Relative was successfully updated.' }
        format.json { render :show, status: :ok, location: @relative }
      else
        format.html { render :edit }
        format.json { render json: @relative.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /relatives/1
  # DELETE /relatives/1.json
  def destroy
    @relative.destroy
    respond_to do |format|
      format.html { redirect_to relatives_url, notice: 'Relative was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_relative
      @relative = Relative.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def relative_params
      params.require(:relative).permit(:name, :bio, :relation, :phone, :patient_id, :avatar, :decision_maker)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to :back, :alert => "Access denied."
    end
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/physicians_helper.rb
module PhysiciansHelper
end

app/helpers/relatives_helper.rb
module RelativesHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <% if current_user.try(:admin?) %>
    <li><%= link_to 'Users', users_path %></li>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>


<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">connectUs</a>
    </div>
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
        <%= render 'layouts/nav_links_for_auth' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'About', page_path('about') %></li>
<li class="divider"></li>
<li><%= link_to 'Providers', physicians_path %></li>
<li class="divider"></li>
<li><%= link_to 'Patients', patients_path %></li>
<li class="divider"></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "connectUs" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "connectUs" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<h4>
The platform will generally work as so:
</h4>
<p>
The patient’s family is requested to visit an online website where they securely upload a picture of themselves, a brief biography of a maximum of 140 characters and their relationship with the patient.
</p>
<p>
When the healthcare provider walks into the room the platform will audibly inform the healthcare provider to wash their hands, which will lead to a positive mental response from the patient and their family.
</p>
<p>
Once the healthcare provider approaches the hand washing station it is generally understood by the patient and their family that the healthcare provider will typically take about one minute to wash and dry their hands. This gives the healthcare provider ample time to understand the personal relationships to the patient that are in the room at any specific time.
</p>
<p>
When the healthcare provider approaches the hand washing station, a monitor will be present with a sensor reader on it where the online platform will automatically link the website to the healthcare provider with their respective RFID badge, so the healthcare provider can look at the the relationships of each member of the patient’s family in the room, as well as a brief biography of each person, for cases where the healthcare provider wishes to get a deeper personal understanding of a specific family member of the patient. 
</p>
<p>
This distinction of each family member’s relationship to the patient will help the healthcare providers make proper judgements on who the decision maker is if the patient is not capable of communicating.
</p>
<p>
From the perspective of the family, the healthcare provider information will always be present at the same monitor at the hand washing station, so that the family members in the ICU at any specific time will be able to know the face and name of each respective healthcare provider that is affiliated with the patient at the time the family member is at the ICU.
</p>
<p>
This product will help to improve the overall healthcare process since it is making it easier for the healthcare provider to show care towards the patient by making the relationships more personal. Thus this will help to increase the communication and make the patient and their family more satisfied, which would lead to a patient recovering more quickly. 
</p>

app/views/patients/_form.html.erb
<%= form_for(@patient, html: {class: 'form-horizontal'}) do |f| %>
  <% if @patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
      <% @patient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :name, class: 'col-sm-2 control-label' %><br>
    <div class="col-sm-10"> 
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>
  <div class="field form-group">
    <%= f.label :bio, class: 'col-sm-2 control-label' %><br>
    <div class="col-sm-10"> 
      <%= f.text_field :bio, class: 'form-control' %>
    </div>
  </div>
  <div class="field form-group">
    <%= f.label :room, class: 'col-sm-2 control-label' %><br>
    <div class="col-sm-10"> 
      <%= f.text_field :room, class: 'form-control' %>
    </div>
  </div>
  <div class="field form-group">
    <%= f.label :checkin_date, class: 'col-sm-2 control-label' %><br>
    <div class="col-sm-10"> 
      <%= f.date_field :checkin_date, class: 'form-control' %>
    </div>
  </div>
  <div class="field form-group">
    <%= f.label :release_date, class: 'col-sm-2 control-label' %><br>
    <div class="col-sm-10"> 
      <%= f.date_field :release_date, class: 'form-control' %>
    </div>
  </div>
  <div class="field form-group">
    <%= f.label :caretakers, class: 'col-sm-2 control-label' %><br>
    <% options = options_from_collection_for_select(Physician.all, 'id', 'name') %>
    <div class="col-sm-10"> 
      <%= f.select :caretakers, options, {}, { :multiple => true, :name => 'caretakers[physician_ids][]' } %>
    </div>
  </div>
  <div class="field form-group">
    <%= f.label :hospital_id, class: 'col-sm-2 control-label' %><br>
    <% options = options_from_collection_for_select(Hospital.all, 'id', 'name') %>
    <div class="col-sm-10"> 
      <%= f.select :hospital_id, options %>
    </div>
  </div>
  <div class="field form-group">
    <%= f.label :Photo, class: 'col-sm-2 control-label' %><br>
    <div class="col-sm-10">
      <%= f.file_field :avatar, class: 'form-control' %>
    </div>
  </div>
  <div class="actions form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit 'Submit', class: 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/patients/edit.html.erb
<h1>Editing Patient</h1>

<ul class="nav nav-tabs" role="tablist">
  <li><%= link_to 'View All Patients', patients_path %></li>
  <li class="active"><%= link_to "#{@patient.name}" %></li>
</ul>

<%= render 'form' %>

<%= link_to 'Show', @patient %> |
<%= link_to 'Back', patients_path %>

app/views/patients/index.html.erb
<h3>Patients</h3>

<ul class="nav nav-tabs" role="tablist">
  <li class="active"><%= link_to 'View All Patients', patients_path %></li>
  <li><%= link_to 'New Patient', new_patient_path %></li>
</ul>

<p id="notice"><%= notice %></p>

<table class="table table-responsive table-striped">
  <thead>
    <tr>
      <th>Photo</th>
      <th>Name</th>
      <th>Room</th>
      <th>Check-in date</th>
      <th>Release date</th>
      <th>Hospital</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td><%= link_to( image_tag(patient.avatar.url(:thumb)), patient) %></td>
        <td><%= patient.name %></td>
        <td><%= patient.room %></td>
        <td><%= patient.checkin_date %></td>
        <td><%= patient.release_date %></td>
        <td><%= Hospital.find(patient.hospital_id).name %></td>
        <td><%= link_to 'Show', patient, class: "btn btn-default btn-sm" %></td>
        <td><%= link_to 'Edit', edit_patient_path(patient), class: "btn btn-default btn-sm" %></td>
        <td><%= link_to 'Destroy', patient, class: "btn btn-default btn-sm", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to new_patient_path, class: "btn btn-success" do %>
  <i class="glyphicon glyphicon-plus"></i> New Patient
<% end %>

app/views/patients/new.html.erb
<h3>New Patient</h3>

<ul class="nav nav-tabs" role="tablist">
  <li><%= link_to 'View All Patients', patients_path %></li>
  <li class="active"><%= link_to 'New Patient', new_patient_path %></li>
</ul>

<%= render 'form' %>

<%= link_to 'Back', patients_path %>

app/views/patients/show.html.erb
<h3>Patient: <%= @patient.name %></h3>

<p id="notice"><%= notice %></p>

<div class="col-sm-4">
  <%= image_tag @patient.avatar.url(:medium) %>
</div>
<div class="col-sm-8">
  <p>
    <strong>Bio:</strong>
    <%= @patient.bio %>
  </p>

  <p>
    <strong>Room:</strong>
    <%= @patient.room %>
  </p>

  <p>
    <strong>Checkin date:</strong>
    <%= @patient.checkin_date %>
  </p>

  <p>
    <strong>Release date:</strong>
    <%= @patient.release_date %>
  </p>

  <p>
    <strong>Hospital:</strong>
    <%= Hospital.find(@patient.hospital_id).name %>
  </p>
</div>

<div class="col-sm-12">
  <table class="table table-responsive table-striped">
  <thead>
    <tr>
      <th class="col-sm-2">Assigned Providers</th>
      <th class="col-sm-2">Name</th>
      <th class="col-sm-4">Bio</th>
      <th class="col-sm-2">Specialty</th>
      <th class="col-sm-2">Hospital</th>
      <th class="col-sm-1" colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @physicians = Physician.all %>
    <% @physicians.each do |physician| %>
      <tr>
        <td><%= link_to( image_tag(physician.avatar.url(:thumb)), physician) %></td>
        <td><%= physician.name %></td>
        <td><%= physician.bio %></td>
        <td><%= physician.specialty %></td>
        <td><%= Hospital.find(physician.hospital_id).name %></td>
        <td><%= link_to 'View', physician, class: "btn btn-default btn-sm" %></td>
        <td><%= link_to 'Edit', edit_physician_path(physician), class: "btn btn-default btn-sm" %></td>
        <td><%= link_to 'Delete', physician, class: "btn btn-default btn-sm", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<div class="col-sm-12">
  <table class="table table-responsive table-striped">
  <thead>
    <tr>
      <th class="col-sm-2">Registered Family & Friends</th>
      <th class="col-sm-2">Name</th>
      <th class="col-sm-4">Bio</th>
      <th class="col-sm-2">Relation</th>
      <th class="col-sm-2">Phone</th>
      <th class="col-sm-1" colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @relatives = Relative.where(patient_id: @patient) %>
    <% @relatives.each do |relative| %>
      <% if relative.decision_maker == true %>
      <tr style="background-color: #3498db;">
      <% else %>
      <tr>
      <% end %>
        <td><%= image_tag relative.avatar.url(:thumb) %></td>
        <td><%= relative.name %></td>
        <td><%= relative.bio %></td>
        <td><%= relative.relation %></td>
        <td><%= relative.phone %></td>
        <td><%= link_to 'View', relative, class: "btn btn-default btn-sm" %></td>
        <td><%= link_to 'Edit', edit_relative_path(relative), class: "btn btn-default btn-sm" %></td>
        <td><%= link_to 'Delete', relative, class: "btn btn-default btn-sm", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<%= link_to new_relative_path, class: "btn btn-success btn-sm" do %>
  <i class="glyphicon glyphicon-plus"></i> Register New Relative
<% end %>
<%= link_to 'Edit Patient Profile', edit_patient_path(@patient), class: "btn btn-default btn-sm" %>

app/views/physicians/edit.html.erb
<h3>Edit Provider</h3>

<ul class="nav nav-tabs" role="tablist">
  <li><%= link_to 'View All Providers', physicians_path %></li>
  <li class="active"><%= link_to 'Edit Provider', edit_physician_path %></li>
</ul>

<%= render 'form' %>

<%= link_to 'Show', @physician, class: "btn btn-default btn-sm" %> |
<%= link_to 'Back', physicians_path, class: "btn btn-default btn-sm" %>

app/views/physicians/index.html.erb
<h3>Providers</h3>

<ul class="nav nav-tabs" role="tablist">
  <li class="active"><%= link_to 'View All Providers', physicians_path %></li>
  <li><%= link_to 'New Provider', new_physician_path %></li>
</ul>

<p id="notice"><%= notice %></p>

<table class="table table-responsive table-striped">
  <thead>
    <tr>
      <th class="col-sm-2">Provider</th>
      <th class="col-sm-2">Name</th>
      <th class="col-sm-4">Bio</th>
      <th class="col-sm-2">Specialty</th>
      <th class="col-sm-2">Hospital</th>
      <th class="col-sm-1" colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @physicians.each do |physician| %>
      <tr>
        <td><%= link_to( image_tag(physician.avatar.url(:thumb)), physician) %></td>
        <td><%= physician.name %></td>
        <td><%= physician.bio %></td>
        <td><%= physician.specialty %></td>
        <td><%= Hospital.find(physician.hospital_id).name %></td>
        <td><%= link_to 'View', physician, class: "btn btn-default btn-sm" %></td>
        <td><%= link_to 'Edit', edit_physician_path(physician), class: "btn btn-default btn-sm" %></td>
        <td><%= link_to 'Delete', physician, class: "btn btn-default btn-sm", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to new_physician_path, class: "btn btn-success" do %>
  <i class="glyphicon glyphicon-plus"></i> New Physician
<% end %>

app/views/physicians/new.html.erb
<h3>New Provider</h3>

<ul class="nav nav-tabs" role="tablist">
  <li><%= link_to 'View All Providers', physicians_path %></li>
  <li class="active"><%= link_to 'New Provider', new_physician_path %></li>
</ul>

<%= render 'form' %>

<%= link_to 'Back', physicians_path, class: "btn btn-default btn-sm" %>

app/views/physicians/show.html.erb
<h3>Provider: <%= @physician.name %></h3>

<p id="notice"><%= notice %></p>

<div class="col-sm-4">
  <%= image_tag @physician.avatar.url(:medium) %>
</div>
<div class="col-sm-8">
  <p>
    <strong>Bio:</strong>
    <%= @physician.bio %>
  </p>

  <p>
    <strong>Specialty:</strong>
    <%= @physician.specialty %>
  </p>

  <p>
    <strong>Hospital:</strong>
  	<%= Hospital.find(@physician.hospital_id).name %>
  </p>
</div>

<%= link_to 'Edit', edit_physician_path(@physician), class: "btn btn-default btn-sm" %> |
<%= link_to 'Back', physicians_path, class: "btn btn-default btn-sm" %>

app/views/relatives/edit.html.erb
<h1>Editing Relative</h1>

<%= render 'form' %>

<%= link_to 'Show', @relative %> |
<%= link_to 'Back', relatives_path %>

app/views/relatives/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Relatives</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Relation</th>
      <th>Phone</th>
      <th>Patient</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @relatives.each do |relative| %>
      <tr>
        <td><%= relative.name %></td>
        <td><%= relative.relation %></td>
        <td><%= relative.phone %></td>
        <td><%= relative.patient_id %></td>
        <td><%= link_to 'Show', relative %></td>
        <td><%= link_to 'Edit', edit_relative_path(relative) %></td>
        <td><%= link_to 'Destroy', relative, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Relative', new_relative_path %>

app/views/relatives/new.html.erb
<ul class="nav nav-tabs" role="tablist">
  <li class="active"><%= link_to 'New Relative', new_relative_path %></li>
</ul>

<%= render 'form' %>

<%= link_to 'Back', patients_path %>

app/views/relatives/show.html.erb
<p id="notice"><%= notice %></p>

<div class="col-sm-4">
  <%= image_tag @relative.avatar.url(:medium) %>
</div>
<div class="col-sm-8">
  <p>
    <strong>Bio:</strong>
    <%= @relative.bio %>
  </p>

  <p>
    <strong>Relation:</strong>
    <%= @relative.relation %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= @relative.phone %>
  </p>

  <p>
    <strong>Patient:</strong>
    <%= Patient.find(@relative.patient_id).name %>
  </p>
</div>

<%= link_to 'Edit', edit_relative_path(@relative), class: "btn btn-default btn-sm" %> |
<%= link_to 'Back to Patient\'s Page', patient_path(@relative.patient_id), class: "btn btn-default btn-sm" %>

app/views/users/_user.html.erb
<td><%= link_to user.name, user %></td>
<td><%= link_to user.email, user %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>

app/views/visitors/index.html.erb
<h3>Welcome</h3>
<p><%= link_to 'Users:', users_path %> <%= User.count %> registered</p>